import { personaHelperTheme } from "./theme.js";

const controlBase = {
  width: "100%",
  boxSizing: "border-box",
  border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
  borderRadius: "0.5rem",
  background: personaHelperTheme.colors.nearBlack,
  color: personaHelperTheme.colors.text,
  fontFamily: personaHelperTheme.fontFamily.body,
  fontSize: "0.8125rem",
  outline: "none",
};

export const formStyles = {
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    minWidth: 0,
  },
  label: {
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
    fontWeight: 400,
  },
  hint: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
  },
  input: {
    ...controlBase,
    minHeight: "2.25rem",
    padding: "0.5rem 0.625rem",
  },
  textarea: {
    ...controlBase,
    minHeight: "7.375rem",
    resize: "vertical",
    padding: "0.5625rem 0.625rem",
    lineHeight: 1.45,
  },
  textareaSmall: {
    ...controlBase,
    minHeight: "4.875rem",
    resize: "vertical",
    padding: "0.5625rem 0.625rem",
    lineHeight: 1.45,
  },
  row: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(9rem, .45fr)",
    gap: "0.625rem",
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.4375rem",
    minHeight: "2.25rem",
    padding: "0.5rem 0.75rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.text,
    color: personaHelperTheme.colors.black,
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontWeight: 600,
  },
  secondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.4375rem",
    minHeight: "2.25rem",
    padding: "0.5rem 0.75rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    cursor: "pointer",
    fontSize: "0.8125rem",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontWeight: 600,
  },
  disabledButton: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  iconGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
  },
  iconButton: {
    width: "1.875rem",
    height: "1.875rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5625rem",
    color: personaHelperTheme.colors.text,
    fontSize: "0.8125rem",
    fontFamily: personaHelperTheme.fontFamily.body,
  },
  switchRow: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "0.75rem",
    color: personaHelperTheme.colors.text,
    fontSize: "0.8125rem",
    fontFamily: personaHelperTheme.fontFamily.body,
    cursor: "pointer",
  },
  switchInput: {
    position: "absolute",
    insetInlineEnd: 0,
    width: "2.625rem",
    height: "1.5rem",
    margin: 0,
    opacity: 0,
    cursor: "pointer",
  },
  switchTrack: {
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    width: "2.625rem",
    height: "1.5rem",
    padding: "0.1875rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "999rem",
    background: personaHelperTheme.colors.nearBlack,
  },
  switchTrackOn: {
    background: personaHelperTheme.colors.text,
  },
  switchThumb: {
    width: "1rem",
    height: "1rem",
    borderRadius: "999rem",
    background: personaHelperTheme.colors.muted,
    transition: "transform 180ms ease-out, background 180ms ease-out",
  },
  switchThumbOn: {
    background: personaHelperTheme.colors.black,
    transform: "translateX(1.125rem)",
  },
};
