const controlBase = {
  width: "100%",
  boxSizing: "border-box",
  border: "1px solid color-mix(in srgb, var(--primary, #ffb3d9) 20%, transparent)",
  borderRadius: 8,
  background: "oklch(14% 0.025 315)",
  color: "oklch(92% 0.018 315)",
  font: "inherit",
  outline: "none",
};

export const formStyles = {
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  },
  label: {
    color: "oklch(84% 0.035 315)",
    fontSize: 12,
    fontWeight: 700,
  },
  hint: {
    color: "oklch(68% 0.03 315)",
    fontSize: 12,
  },
  input: {
    ...controlBase,
    minHeight: 36,
    padding: "8px 10px",
  },
  textarea: {
    ...controlBase,
    minHeight: 118,
    resize: "vertical",
    padding: "9px 10px",
    lineHeight: 1.45,
  },
  textareaSmall: {
    ...controlBase,
    minHeight: 78,
    resize: "vertical",
    padding: "9px 10px",
    lineHeight: 1.45,
  },
  row: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(130px, .45fr)",
    gap: 10,
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: 36,
    padding: "8px 12px",
    border: "1px solid color-mix(in srgb, var(--primary, #ffb3d9) 22%, transparent)",
    borderRadius: 8,
    background: "var(--primary, #ffb3d9)",
    color: "oklch(15% 0.025 315)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 750,
  },
  iconGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  iconButton: {
    width: 30,
    height: 30,
    border: "1px solid color-mix(in srgb, var(--primary, #ffb3d9) 16%, transparent)",
    borderRadius: 7,
    background: "oklch(18% 0.03 315)",
    color: "oklch(82% 0.04 315)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    color: "oklch(86% 0.026 315)",
    fontSize: 13,
  },
};
