import { personaHelperTheme } from "./theme.js";

const controlBase = {
  width: "100%",
  boxSizing: "border-box",
  border: `1px solid ${personaHelperTheme.colors.charcoal}`,
  borderRadius: 8,
  background: personaHelperTheme.colors.nearBlack,
  color: personaHelperTheme.colors.text,
  fontFamily: personaHelperTheme.fontFamily.body,
  fontSize: 13,
  outline: "none",
};

export const formStyles = {
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minWidth: 0,
  },
  label: {
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: 12,
    fontWeight: 400,
  },
  hint: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: 12,
  },
  input: {
    ...controlBase,
    minHeight: 36,
    padding: "8px 10px",
  },
  textarea: {
    ...controlBase,
    minHeight: 118,
    resize: "vertical",
    padding: "9px 10px",
    lineHeight: 1.45,
  },
  textareaSmall: {
    ...controlBase,
    minHeight: 78,
    resize: "vertical",
    padding: "9px 10px",
    lineHeight: 1.45,
  },
  row: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(130px, .45fr)",
    gap: 10,
  },
  primaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    minHeight: 36,
    padding: "8px 12px",
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: personaHelperTheme.colors.text,
    color: personaHelperTheme.colors.black,
    cursor: "pointer",
    fontSize: 13,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontWeight: 600,
  },
  iconGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  iconButton: {
    width: 30,
    height: 30,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 7,
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    color: personaHelperTheme.colors.text,
    fontSize: 13,
    fontFamily: personaHelperTheme.fontFamily.body,
  },
};
