import { personaHelperTheme } from "./theme.js";

export const navigationStyles = {
  shell: {
    display: "grid",
    gridTemplateColumns: "3rem minmax(0, 1fr)",
    minHeight: 0,
    flex: 1,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
  },
  rail: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.625rem 0.375rem",
    borderRight: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    background: personaHelperTheme.colors.nearBlack,
  },
  railButton: {
    position: "relative",
    width: "2.125rem",
    height: "2.125rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
  },
  railButtonActive: {
    background: personaHelperTheme.colors.charcoal,
    borderColor: personaHelperTheme.colors.text,
    color: personaHelperTheme.colors.text,
  },
  railActiveIndicator: {
    position: "absolute",
    left: "-0.375rem",
    width: "0.1875rem",
    height: "1.125rem",
    borderRadius: "0.125rem",
    background: personaHelperTheme.colors.text,
  },
  railTooltip: {
    position: "absolute",
    left: "2.625rem",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10000,
    padding: "0.3125rem 0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.375rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.text,
    fontSize: "0.6875rem",
    fontFamily: personaHelperTheme.fontFamily.ui,
    lineHeight: "0.875rem",
    whiteSpace: "nowrap",
    boxShadow: "0 0.5rem 1.125rem rgba(0,0,0,0.35)",
    pointerEvents: "none",
  },
  main: {
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: "column",
    background: "rgba(0, 0, 0, 0.9)",
  },
  tabs: {
    display: "flex",
    alignItems: "center",
    gap: "0.375rem",
    padding: "0.625rem 0.75rem",
    borderBottom: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    background: personaHelperTheme.colors.nearBlack,
    fontFamily: personaHelperTheme.fontFamily.heading,
    overflowX: "auto",
  },
  tabButton: {
    minWidth: 0,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "0.75rem",
    fontWeight: 600,
    lineHeight: "1rem",
    padding: "0.375rem 0.625rem",
    whiteSpace: "nowrap",
  },
  tabButtonActive: {
    background: personaHelperTheme.colors.charcoal,
    color: personaHelperTheme.colors.text,
    borderColor: personaHelperTheme.colors.text,
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "0.75rem",
    background: "transparent",
  },
};
