export const navigationStyles = {
  shell: {
    display: "flex",
    minHeight: 0,
    flex: 1,
    background: "oklch(17% 0.03 315)",
  },
  rail: {
    width: 52,
    flex: "0 0 52px",
    padding: "10px 8px",
    borderRight: "1px solid color-mix(in srgb, var(--primary, #ffb3d9) 16%, transparent)",
    background: "oklch(14% 0.028 315)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  railButton: {
    position: "relative",
    width: 36,
    height: 36,
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "oklch(78% 0.035 315)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  railButtonActive: {
    background: "oklch(24% 0.045 315)",
    borderColor: "color-mix(in srgb, var(--primary, #ffb3d9) 24%, transparent)",
    color: "var(--primary, #ffb3d9)",
  },
  railActiveIndicator: {
    position: "absolute",
    left: -5,
    width: 3,
    height: 20,
    borderRadius: 999,
    background: "var(--primary, #ffb3d9)",
  },
  railTooltip: {
    position: "absolute",
    left: 44,
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 2,
    padding: "5px 8px",
    borderRadius: 6,
    background: "oklch(12% 0.024 315)",
    color: "oklch(92% 0.02 315)",
    border: "1px solid color-mix(in srgb, var(--primary, #ffb3d9) 20%, transparent)",
    whiteSpace: "nowrap",
    boxShadow: "0 6px 18px rgba(0,0,0,.25)",
  },
  main: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  tabs: {
    display: "flex",
    gap: 6,
    padding: "10px 12px 0",
    background: "oklch(16% 0.03 315)",
  },
  tabButton: {
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "oklch(76% 0.035 315)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 650,
    padding: "7px 10px",
  },
  tabButtonActive: {
    background: "oklch(24% 0.04 315)",
    color: "oklch(94% 0.024 315)",
    borderColor: "color-mix(in srgb, var(--primary, #ffb3d9) 22%, transparent)",
  },
  content: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: "14px 14px 48px",
  },
};
