import { personaHelperTheme } from "./theme.js";

export const navigationStyles = {
  shell: {
    display: "grid",
    gridTemplateColumns: "48px minmax(0, 1fr)",
    minHeight: 0,
    flex: 1,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
  },
  rail: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: "10px 6px",
    borderRight: `1px solid ${personaHelperTheme.colors.charcoal}`,
    background: personaHelperTheme.colors.nearBlack,
  },
  railButton: {
    position: "relative",
    width: 34,
    height: 34,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
  },
  railButtonActive: {
    background: personaHelperTheme.colors.charcoal,
    borderColor: personaHelperTheme.colors.text,
    color: personaHelperTheme.colors.text,
  },
  railActiveIndicator: {
    position: "absolute",
    left: -6,
    width: 3,
    height: 18,
    borderRadius: 2,
    background: personaHelperTheme.colors.text,
  },
  railTooltip: {
    position: "absolute",
    left: 42,
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10000,
    padding: "5px 8px",
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 6,
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.text,
    fontSize: 11,
    fontFamily: personaHelperTheme.fontFamily.ui,
    lineHeight: "14px",
    whiteSpace: "nowrap",
    boxShadow: "0 8px 18px rgba(0,0,0,0.35)",
    pointerEvents: "none",
  },
  main: {
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    flexDirection: "column",
    background: "rgba(0, 0, 0, 0.9)",
  },
  tabs: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "10px 12px",
    borderBottom: `1px solid ${personaHelperTheme.colors.charcoal}`,
    background: personaHelperTheme.colors.nearBlack,
    fontFamily: personaHelperTheme.fontFamily.heading,
    overflowX: "auto",
  },
  tabButton: {
    minWidth: 0,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: 12,
    fontWeight: 600,
    lineHeight: "16px",
    padding: "6px 10px",
    whiteSpace: "nowrap",
  },
  tabButtonActive: {
    background: personaHelperTheme.colors.charcoal,
    color: personaHelperTheme.colors.text,
    borderColor: personaHelperTheme.colors.text,
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: 12,
    background: "transparent",
  },
};
