import { personaHelperTheme } from "./theme.js";

export const overlayStyles = {
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 10020,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.62)",
    padding: 20,
  },
  modal: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    width: "min(640px, calc(100vw - 40px))",
    maxHeight: "min(680px, calc(100vh - 40px))",
    overflowY: "auto",
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: "rgba(0, 0, 0, 0.97)",
    boxShadow: "0 24px 70px rgba(0,0,0,0.68)",
    color: personaHelperTheme.colors.text,
    padding: 14,
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  modalTitle: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "22px",
  },
  modalNote: {
    borderTop: `1px solid ${personaHelperTheme.colors.charcoal}`,
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: 12,
    lineHeight: "18px",
    paddingTop: 10,
  },
  snackbar: {
    position: "fixed",
    left: 18,
    bottom: 18,
    zIndex: 10030,
    maxWidth: "min(520px, calc(100vw - 36px))",
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: "rgba(0, 0, 0, 0.94)",
    boxShadow: "0 14px 42px rgba(0,0,0,0.48)",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: 12,
    lineHeight: "18px",
    padding: "9px 12px",
    pointerEvents: "none",
    animation: "ph-snackbar-in 160ms ease-out",
  },
};
