import { personaHelperTheme } from "./theme.js";

export const overlayStyles = {
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 10020,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.62)",
    padding: "1.25rem",
  },
  modal: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    width: "min(40rem, calc(100vw - 2.5rem))",
    maxHeight: "min(42.5rem, calc(100vh - 2.5rem))",
    overflowY: "auto",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(0, 0, 0, 0.97)",
    boxShadow: "0 1.5rem 4.375rem rgba(0,0,0,0.68)",
    color: personaHelperTheme.colors.text,
    padding: "0.875rem",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
  },
  modalTitle: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "1rem",
    fontWeight: 500,
    lineHeight: "1.375rem",
  },
  modalNote: {
    borderTop: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: "1.125rem",
    paddingTop: "0.625rem",
  },
  snackbar: {
    position: "fixed",
    left: "1.125rem",
    bottom: "1.125rem",
    zIndex: 10030,
    maxWidth: "min(32.5rem, calc(100vw - 2.25rem))",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(0, 0, 0, 0.94)",
    boxShadow: "0 0.875rem 2.625rem rgba(0,0,0,0.48)",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: "1.125rem",
    padding: "0.5625rem 0.75rem",
    pointerEvents: "none",
    animation: "ph-snackbar-in 160ms ease-out",
  },
};
