import { personaHelperTheme } from "./theme.js";

export const promptPickerStyles = {
  selectedCard: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "0.625rem",
    alignItems: "start",
    minWidth: 0,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(17, 17, 17, 0.9)",
    padding: "0.75rem",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 10020,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.68)",
    padding: "1.125rem",
  },
  modal: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    width: "min(72rem, calc(100vw - 2.25rem))",
    height: "min(82vh, calc(100vh - 2.25rem))",
    minHeight: 0,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(0, 0, 0, 0.97)",
    boxShadow: "0 1.5rem 4.375rem rgba(0,0,0,0.68)",
    color: personaHelperTheme.colors.text,
    padding: "0.875rem",
  },
  modalHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "0.625rem",
    alignItems: "start",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    minWidth: 0,
  },
  controls: {
    display: "grid",
    gridTemplateColumns: "minmax(14rem, 1fr) minmax(11rem, .42fr) minmax(8rem, .32fr)",
    gap: "0.5rem",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(14rem, 1fr))",
    gap: "0.625rem",
    minHeight: 0,
    overflowY: "auto",
    paddingRight: "0.125rem",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minHeight: "8.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(17, 17, 17, 0.86)",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    padding: "0.625rem",
    textAlign: "left",
  },
  cardSelected: {
    borderColor: personaHelperTheme.colors.text,
    background: "rgba(34, 34, 34, 0.9)",
  },
  cardHeader: {
    display: "grid",
    gridTemplateColumns: "1.125rem minmax(0, 1fr)",
    gap: "0.4375rem",
    alignItems: "center",
  },
  cardTitle: {
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "0.875rem",
    lineHeight: "1.125rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardDescription: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: "1.0625rem",
  },
  cardMetaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.5rem",
    marginTop: "auto",
  },
  cardMeta: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.6875rem",
    lineHeight: "0.875rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    minHeight: 0,
    overflowY: "auto",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(16rem, 1fr))",
    gap: "0.625rem",
  },
  detailBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "0.4375rem",
    minWidth: 0,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(17, 17, 17, 0.78)",
    padding: "0.625rem",
  },
  detailScrollBlock: {
    maxHeight: "14rem",
    overflowY: "auto",
  },
  promptBody: {
    maxHeight: "16rem",
    margin: 0,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: "1.125rem",
  },
  entryPreview: {
    flex: "1 1 auto",
    maxHeight: "none",
    minHeight: 0,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.nearBlack,
    padding: "0.75rem",
  },
  searchShell: {
    display: "grid",
    gridTemplateColumns: "1rem minmax(0, 1fr)",
    alignItems: "center",
    gap: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.nearBlack,
    color: personaHelperTheme.colors.muted,
    padding: "0 0.625rem",
  },
  searchInput: {
    minHeight: "2.25rem",
    minWidth: 0,
    border: 0,
    outline: "none",
    background: "transparent",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.8125rem",
  },
};
