import { personaHelperTheme } from "./theme.js";

export const promptPickerStyles = {
  selectedCard: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 10,
    alignItems: "start",
    minWidth: 0,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: "rgba(17, 17, 17, 0.9)",
    padding: 12,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 10020,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.68)",
    padding: 18,
  },
  modal: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    width: "min(980px, calc(100vw - 36px))",
    height: "min(760px, calc(100vh - 36px))",
    minHeight: 0,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: "rgba(0, 0, 0, 0.97)",
    boxShadow: "0 24px 70px rgba(0,0,0,0.68)",
    color: personaHelperTheme.colors.text,
    padding: 14,
  },
  modalHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 10,
    alignItems: "start",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  controls: {
    display: "grid",
    gridTemplateColumns: "minmax(180px, 1fr) minmax(150px, .42fr) minmax(120px, .32fr)",
    gap: 8,
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(190px, 1fr))",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: 2,
  },
  card: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 136,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: "rgba(17, 17, 17, 0.86)",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    padding: 10,
    textAlign: "left",
  },
  cardHeader: {
    display: "grid",
    gridTemplateColumns: "18px minmax(0, 1fr)",
    gap: 7,
    alignItems: "center",
  },
  cardTitle: {
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: 14,
    lineHeight: "18px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardDescription: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: 12,
    lineHeight: "17px",
  },
  cardMetaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: "auto",
  },
  cardMeta: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: 11,
    lineHeight: "14px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 10,
  },
  detailBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
    minWidth: 0,
    border: `1px solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: 8,
    background: "rgba(17, 17, 17, 0.78)",
    padding: 10,
  },
  promptBody: {
    maxHeight: 210,
    margin: 0,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: 12,
    lineHeight: "18px",
  },
};
