import { personaHelperTheme } from "./theme.js";

export const viewStyles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(18rem, 22rem)",
    gap: "0.875rem",
    alignItems: "start",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    minWidth: 0,
  },
  pageHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1875rem",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1875rem",
    paddingTop: "0.375rem",
  },
  fieldGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(12rem, 1fr))",
    gap: "0.625rem",
  },
  cleanList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    margin: 0,
    paddingInlineStart: "1rem",
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.45,
  },
  heading: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "1.125rem",
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  title: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.875rem",
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1.3,
  },
  muted: {
    margin: 0,
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.4,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
  },
  scrollStack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    maxHeight: "18rem",
    minHeight: 0,
    overflowY: "auto",
    paddingRight: "0.125rem",
  },
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    minWidth: 0,
    padding: "0.75rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(17, 17, 17, 0.9)",
  },
  selectablePanel: {
    cursor: "pointer",
    transition: "border-color 180ms ease-out, background 180ms ease-out",
  },
  selectedPanel: {
    borderColor: personaHelperTheme.colors.text,
    background: "rgba(28, 28, 28, 0.94)",
  },
  panelHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "0.625rem",
  },
  disclosureButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
    width: "100%",
    minHeight: "2.375rem",
    padding: "0 0.125rem",
    border: 0,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "1.125rem",
    lineHeight: 1.25,
    textAlign: "left",
  },
  disclosureButtonSmall: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
    width: "100%",
    minHeight: "2rem",
    padding: "0 0.125rem",
    border: 0,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.875rem",
    lineHeight: 1.25,
    textAlign: "left",
  },
  cardToolbar: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
    flexShrink: 0,
  },
  inlineTitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4375rem",
    minWidth: 0,
  },
  debugActionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "0.375rem",
    flexShrink: 0,
  },
  draftingIndicator: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4375rem",
    minHeight: "2.25rem",
    color: personaHelperTheme.colors.text,
  },
  draftingStatus: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "2.25rem",
    padding: "0 0.125rem",
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
    lineHeight: 1.2,
  },
  draftingStatusText: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.015625rem",
    minWidth: "9.5rem",
    fontFamily: personaHelperTheme.fontFamily.ui,
    letterSpacing: 0,
  },
  draftingStatusChar: {
    display: "inline-block",
    minWidth: "0.25rem",
    transition: "color 260ms ease-out",
  },
  draftingSpinner: {
    animation: "ph-spin 900ms linear infinite",
    color: personaHelperTheme.colors.text,
    flexShrink: 0,
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
  },
  badgeRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.3125rem",
    minHeight: "1.5rem",
    padding: "0.1875rem 0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    color: personaHelperTheme.colors.text,
    background: personaHelperTheme.colors.black,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.6875rem",
    lineHeight: 1.2,
  },
  badgeMuted: {
    color: personaHelperTheme.colors.muted,
    background: personaHelperTheme.colors.nearBlack,
    borderStyle: "dashed",
  },
  contextValue: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1875rem",
    minWidth: 0,
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
  },
  contextLabel: {
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.6875rem",
    lineHeight: 1.2,
  },
  contextText: {
    overflow: "hidden",
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.3,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  subjectOption: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "2.5rem",
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    textAlign: "left",
  },
  subjectOptionSelected: {
    borderColor: personaHelperTheme.colors.text,
    background: "rgba(32, 32, 32, 0.96)",
  },
  subjectCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(13rem, 1fr))",
    gap: "0.5rem",
    minHeight: 0,
    maxHeight: "24rem",
    overflowY: "auto",
    paddingRight: "0.125rem",
  },
  subjectSelectCard: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "2.5rem",
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
  },
  subjectAvatarFrame: {
    position: "relative",
    width: "1.375rem",
    height: "1.375rem",
    flex: "0 0 1.375rem",
    overflow: "hidden",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.375rem",
    background: personaHelperTheme.colors.black,
  },
  subjectAvatarImage: {
    display: "block",
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  subjectText: {
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
    minWidth: 0,
  },
  targetRow: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "2.25rem",
    padding: "0.375rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
  },
  goalLibraryCard: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minWidth: 0,
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    transition: "border-color 180ms ease-out, background 180ms ease-out",
  },
  goalLibraryCardSelected: {
    borderColor: personaHelperTheme.colors.text,
    background: "rgba(32, 32, 32, 0.96)",
  },
  goalLibrarySelectButton: {
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr) auto",
    alignItems: "start",
    gap: "0.625rem",
    width: "100%",
    padding: 0,
    border: 0,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    textAlign: "left",
  },
  goalDescription: {
    display: "-webkit-box",
    overflow: "hidden",
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.35,
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
  },
  goalCardActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
    paddingTop: "0.5rem",
    borderTop: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
  },
  libraryLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(13rem, 0.34fr) minmax(0, 1fr)",
    gap: "0.75rem",
    alignItems: "start",
    minWidth: 0,
  },
  libraryLayoutRailClosed: {
    gridTemplateColumns: "3.25rem minmax(0, 1fr)",
  },
  libraryRail: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    minWidth: 0,
    padding: "0.75rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(17, 17, 17, 0.9)",
  },
  libraryRailCollapsed: {
    alignItems: "center",
    padding: "0.5rem",
  },
  libraryDetail: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    minWidth: 0,
  },
  sideToolTabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "0.375rem",
    padding: "0.1875rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
  },
  sideToolTab: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.375rem",
    minHeight: "2rem",
    padding: "0.375rem 0.5rem",
    border: 0,
    borderRadius: "0.375rem",
    background: "transparent",
    color: personaHelperTheme.colors.muted,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
    lineHeight: 1.2,
  },
  sideToolTabActive: {
    background: personaHelperTheme.colors.charcoal,
    color: personaHelperTheme.colors.text,
  },
  railIconStack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "0.375rem",
  },
  sideRailDivider: {
    width: "1.5rem",
    height: "0.0625rem",
    background: personaHelperTheme.colors.charcoal,
  },
  libraryListButton: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "2.5rem",
    width: "100%",
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    textAlign: "left",
  },
  libraryListButtonSelected: {
    borderColor: personaHelperTheme.colors.text,
    background: "rgba(32, 32, 32, 0.96)",
  },
  nodeTree: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  nodeRow: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minWidth: 0,
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
  },
  nodeMain: {
    display: "grid",
    gridTemplateColumns: "minmax(7rem, 0.26fr) minmax(0, 1fr)",
    gap: "0.5rem",
    alignItems: "center",
  },
  taskDraftRow: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minWidth: 0,
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(8, 8, 8, 0.7)",
  },
  taskDraftMain: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "0.5rem",
    alignItems: "center",
  },
  focusedNodeText: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.8125rem",
    lineHeight: 1.45,
    whiteSpace: "normal",
    overflowWrap: "anywhere",
  },
  taskLinkRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "0.5rem",
    minHeight: "2.5rem",
    width: "100%",
    padding: "0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    textAlign: "left",
  },
  taskHeaderToggle: {
    minWidth: "12rem",
  },
  librarySwitch: {
    minWidth: "10rem",
  },
  taskCheckLabel: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    minWidth: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.8125rem",
  },
  taskCompletionSwitch: {
    width: "7.25rem",
    flex: "0 0 7.25rem",
  },
  progressPill: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "3.25rem",
    minHeight: "1.625rem",
    padding: "0.25rem 0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "999rem",
    background: personaHelperTheme.colors.nearBlack,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
  },
  nodeControls: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.375rem",
  },
  nodeAddRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "0.375rem",
    alignItems: "center",
  },
  nodeAddPanel: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(8rem, 10rem) minmax(4rem, 5rem) auto",
    gap: "0.375rem",
    alignItems: "center",
  },
  body: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.8125rem",
    lineHeight: 1.5,
  },
  note: {
    margin: 0,
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.45,
  },
  kicker: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.6875rem",
    fontWeight: 750,
    textTransform: "uppercase",
  },
  empty: {
    padding: "0.875rem",
    border: `0.0625rem dashed ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    color: personaHelperTheme.colors.muted,
    background: personaHelperTheme.colors.nearBlack,
    fontSize: "0.8125rem",
    fontFamily: personaHelperTheme.fontFamily.body,
    lineHeight: 1.45,
  },
  rawViewer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minHeight: 0,
  },
  rawTabs: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
  },
  rawTabButton: {
    minHeight: "1.75rem",
    padding: "0.3125rem 0.625rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
    lineHeight: 1.2,
  },
  rawTabButtonActive: {
    background: personaHelperTheme.colors.charcoal,
    borderColor: personaHelperTheme.colors.text,
    color: personaHelperTheme.colors.text,
  },
  rawOutput: {
    minHeight: "16rem",
    maxHeight: "40vh",
    margin: 0,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
    color: personaHelperTheme.colors.text,
    background: personaHelperTheme.colors.nearBlack,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    padding: "0.625rem",
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.45,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 80,
    display: "grid",
    placeItems: "center",
    padding: "1rem",
    background: "rgba(5, 5, 5, 0.62)",
  },
  modalPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    width: "min(40rem, 100%)",
    maxHeight: "min(42rem, 86vh)",
    minWidth: 0,
    overflow: "hidden",
    padding: "0.875rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.nearBlack,
    boxShadow: "0 1rem 2.5rem rgba(0, 0, 0, 0.38)",
  },
  mapModalPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    width: "min(58rem, calc(100vw - 2rem))",
    maxHeight: "calc(100vh - 2rem)",
    minWidth: 0,
    padding: "1rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.75rem",
    background: personaHelperTheme.colors.nearBlack,
    boxShadow: "0 1rem 3rem rgba(0, 0, 0, 0.45)",
  },
  flowCanvas: {
    position: "relative",
    height: "min(34rem, 68vh)",
    minHeight: "20rem",
    overflow: "hidden",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.black,
  },
  flowNode: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    width: "12.5rem",
    minHeight: "3.5rem",
    padding: "0.625rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: personaHelperTheme.colors.nearBlack,
    boxShadow: "0 0.5rem 1.5rem rgba(0, 0, 0, 0.28)",
  },
  flowNodeFocused: {
    borderColor: personaHelperTheme.colors.text,
  },
  flowNodeDone: {
    opacity: 0.62,
  },
};
