import { personaHelperTheme } from "./theme.js";

export const viewStyles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(18rem, 22rem)",
    gap: "0.875rem",
    alignItems: "start",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.75rem",
    minWidth: 0,
  },
  pageHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1875rem",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "0.1875rem",
    paddingTop: "0.375rem",
  },
  fieldGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(12rem, 1fr))",
    gap: "0.625rem",
  },
  heading: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "1.125rem",
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  title: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.875rem",
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: 1.3,
  },
  muted: {
    margin: 0,
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.4,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
  },
  scrollStack: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    maxHeight: "18rem",
    minHeight: 0,
    overflowY: "auto",
    paddingRight: "0.125rem",
  },
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: "0.625rem",
    minWidth: 0,
    padding: "0.75rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    background: "rgba(17, 17, 17, 0.9)",
  },
  selectablePanel: {
    cursor: "pointer",
    transition: "border-color 180ms ease-out, background 180ms ease-out",
  },
  selectedPanel: {
    borderColor: personaHelperTheme.colors.text,
    background: "rgba(28, 28, 28, 0.94)",
  },
  panelHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "0.625rem",
  },
  disclosureButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
    width: "100%",
    minHeight: "2.375rem",
    padding: "0 0.125rem",
    border: 0,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.heading,
    fontSize: "1.125rem",
    lineHeight: 1.25,
    textAlign: "left",
  },
  disclosureButtonSmall: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
    width: "100%",
    minHeight: "2rem",
    padding: "0 0.125rem",
    border: 0,
    background: "transparent",
    color: personaHelperTheme.colors.text,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.875rem",
    lineHeight: 1.25,
    textAlign: "left",
  },
  cardToolbar: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
    flexShrink: 0,
  },
  debugActionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "0.375rem",
    flexShrink: 0,
  },
  draftingStatus: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "2.25rem",
    padding: "0 0.125rem",
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
    lineHeight: 1.2,
  },
  draftingStatusText: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.015625rem",
    minWidth: "9.5rem",
    fontFamily: personaHelperTheme.fontFamily.ui,
    letterSpacing: 0,
  },
  draftingStatusChar: {
    display: "inline-block",
    minWidth: "0.25rem",
    transition: "color 260ms ease-out",
  },
  draftingSpinner: {
    animation: "ph-spin 900ms linear infinite",
    color: personaHelperTheme.colors.text,
    flexShrink: 0,
  },
  cardMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.625rem",
  },
  badgeRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.375rem",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: "1.5rem",
    padding: "0.1875rem 0.5rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    color: personaHelperTheme.colors.text,
    background: personaHelperTheme.colors.black,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.6875rem",
    lineHeight: 1.2,
  },
  badgeMuted: {
    color: personaHelperTheme.colors.muted,
    background: personaHelperTheme.colors.nearBlack,
    borderStyle: "dashed",
  },
  body: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.8125rem",
    lineHeight: 1.5,
  },
  note: {
    margin: 0,
    color: personaHelperTheme.colors.muted,
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.45,
  },
  kicker: {
    margin: 0,
    color: personaHelperTheme.colors.text,
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.6875rem",
    fontWeight: 750,
    textTransform: "uppercase",
  },
  empty: {
    padding: "0.875rem",
    border: `0.0625rem dashed ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.5rem",
    color: personaHelperTheme.colors.muted,
    background: personaHelperTheme.colors.nearBlack,
    fontSize: "0.8125rem",
    fontFamily: personaHelperTheme.fontFamily.body,
    lineHeight: 1.45,
  },
  rawViewer: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    minHeight: 0,
  },
  rawTabs: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.375rem",
  },
  rawTabButton: {
    minHeight: "1.75rem",
    padding: "0.3125rem 0.625rem",
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    background: personaHelperTheme.colors.black,
    color: personaHelperTheme.colors.muted,
    cursor: "pointer",
    fontFamily: personaHelperTheme.fontFamily.ui,
    fontSize: "0.75rem",
    lineHeight: 1.2,
  },
  rawTabButtonActive: {
    background: personaHelperTheme.colors.charcoal,
    borderColor: personaHelperTheme.colors.text,
    color: personaHelperTheme.colors.text,
  },
  rawOutput: {
    minHeight: "16rem",
    maxHeight: "40vh",
    margin: 0,
    overflowY: "auto",
    whiteSpace: "pre-wrap",
    color: personaHelperTheme.colors.text,
    background: personaHelperTheme.colors.nearBlack,
    border: `0.0625rem solid ${personaHelperTheme.colors.charcoal}`,
    borderRadius: "0.4375rem",
    padding: "0.625rem",
    fontFamily: personaHelperTheme.fontFamily.body,
    fontSize: "0.75rem",
    lineHeight: 1.45,
  },
};
