export const viewStyles = {
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(260px, 320px)",
    gap: 14,
    alignItems: "start",
  },
  stack: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minWidth: 0,
  },
  pageHeader: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  heading: {
    margin: 0,
    color: "oklch(94% 0.024 315)",
    fontSize: 18,
    fontWeight: 750,
    letterSpacing: 0,
    lineHeight: 1.25,
  },
  title: {
    margin: 0,
    color: "oklch(94% 0.024 315)",
    fontSize: 14,
    fontWeight: 750,
    letterSpacing: 0,
    lineHeight: 1.3,
  },
  muted: {
    margin: 0,
    color: "oklch(70% 0.032 315)",
    fontSize: 12,
    lineHeight: 1.4,
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minWidth: 0,
    padding: 12,
    border: "1px solid color-mix(in srgb, var(--primary, #ffb3d9) 18%, transparent)",
    borderRadius: 8,
    background: "oklch(20% 0.032 315)",
  },
  panelHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  body: {
    margin: 0,
    color: "oklch(88% 0.022 315)",
    fontSize: 13,
    lineHeight: 1.5,
  },
  note: {
    margin: 0,
    color: "oklch(78% 0.04 315)",
    fontSize: 12,
    lineHeight: 1.45,
  },
  kicker: {
    margin: 0,
    color: "var(--primary, #ffb3d9)",
    fontSize: 11,
    fontWeight: 750,
    textTransform: "uppercase",
  },
  empty: {
    padding: 14,
    border: "1px dashed color-mix(in srgb, var(--primary, #ffb3d9) 20%, transparent)",
    borderRadius: 8,
    color: "oklch(74% 0.035 315)",
    background: "oklch(17% 0.028 315)",
    fontSize: 13,
    lineHeight: 1.45,
  },
};
